Air Passengers Data Set 
=================================================

Column {.tabset}
--------------------------------------

### Basic Concepts

Before we begin analysing such data, we first need to create a mathematical
framework to work in. Fortunately, we do not need anything too
complicated, and for a finite time-series of length $N$, we model the time
series as a sequence of $N$ random variables, $X_i$, with $i = 1, 2, ..., N$.

Note that each individual $X_i$ is a wholly separate random variable: we only
ever have a single measurement from each random variable. In many cases we
simplify this, but it is important to understand and appreciate that such
simplifications are just that. Time series are difficult to analyse.

Before we get to any of that though, and before we try to build any kind of
models for the data, we always start with visualising the data. Often, a simple
plot of the data helps use pick out aspects to analyse and incorporate into the
models. For time series, one of the first things to do is the *time plot*, a
simple plot of the data over time.

For the passenger data, a few aspects stand out that are very common in time
series. It is apparent that the numbers increase over time, and this systematic
change in the data is called the *trend*. Often, approximating the trend as a
linear function of time is adequate for many data sets.

### Plotting

A famous example of a time-series is count of airline passengers in the US,
as shown in the figure below. This is a simple univariate time-series, with
measurements taken on a monthly basis over a number of years, each datum
consisting of a single number - the number of passengers travelling via
a commercial flight that month.

```{r plot_air_passenger_timeseries, echo=TRUE}
plot(AirPassengers)
```


### Data 

A repeating pattern in the data that occurs over the period of the data (in
this case, each year), is called the *seasonal variation*, though a more
general concept of 'season' is implied --- it often will not coincide with the
seasons of the calendar.

A slightly more generalised concept from the seasonality is that of *cycles*,
repeating patterns in the data that do not correspond to the natural fixed
periods of the model. None of these are apparent in the air passenger data, and
accounting for them are beyond the scope of this introductory tutorial.

Finally, another important benefit of visualising the data is that it helps
identify possible *outliers* and *erroneous* data.

In many cases, we will also be dealing with time series that have multiple
values at all, many or some of the points in time.

Often, these values will be related in some ways, and we will want to analyse
those relationships also. In fact, one of the most efficient methods of
prediction is to find *leading indicators* for the value or values you wish to
predict --- you can often use the current values of the leading indicators to
make inference on future values of the related quantities.

The fact that this is one of the best methods in time series analysis says a
lot about the difficulty of prediction (Yogi Berra, a US baseball player noted
for his pithy statements, once said "Prediction is difficult, especially about
the future").


### Example Timeseries

In this workshop we will look at a number of different time-series, discussed
here.

This data comes in a few different format, and this workshop discusses methods
for analysing this data in a common format.

