
### Forecast 

```{r}
library(forecast)


```

```{r}
# save a numeric vector containing 72 monthly observations
# from Jan 2009 to Dec 2014 as a time series object
myvector <- sort(rnorm(72,100,4)) + rnorm(72,5,1)
myts <- ts(myvector, start=c(2009, 1), end=c(2014, 12), frequency=12) 

```

```{r}
# subset the time series (June 2014 to December 2014)
myts2 <- window(myts, start=c(2014, 6), end=c(2014, 12)) 

```

```{r}
# plot series
plot(myts)

```

```{r}
# Seasonal decomposition
fit <- stl(myts, s.window="period")
plot(fit)

```

```{r}

# additional plots
monthplot(myts)
library(forecast)
seasonplot(myts)
```

```{r}
# simple exponential - models level
fit <- HoltWinters(myts, beta=FALSE, gamma=FALSE)
# double exponential - models level and trend
fit <- HoltWinters(myts, gamma=FALSE)
# triple exponential - models level, trend, and seasonal components
fit <- HoltWinters(myts)

```

```{r}

# predictive accuracy
library(forecast)
accuracy(fit)
```

```{r}
# predict next three future values
library(forecast)
forecast(fit, 3)
plot(forecast(fit, 3))
```

